# Generated by Django 3.0.7 on 2020-12-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0035_auto_20200928_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='имя')),
                ('lastname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
                ('address', models.CharField(max_length=30, verbose_name='адрес')),
                ('order', models.CharField(max_length=30, verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказ',
            },
        ),
    ]
