# Generated by Django 3.0.7 on 2020-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0036_customerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='order',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order_details',
            field=models.CharField(blank=True, max_length=30, verbose_name='детали заказа'),
        ),
    ]
