# Generated by Django 3.0.7 on 2020-12-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20201210_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order_details',
            field=models.CharField(max_length=30, verbose_name='details'),
        ),
    ]
