# Generated by Django 3.0.7 on 2020-12-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20201210_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='order_details',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_items', to='foodcartapp.CustomerOrder'),
        ),
    ]
