# Generated by Django 3.0.7 on 2020-12-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20201216_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
    ]
