# Generated by Django 3.0.7 on 2020-12-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20201216_2000'),
    ]

    operations = [
        migrations.AlterField(            
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='foodcartapp.Product', verbose_name='бургер'),
            preserve_default=False,
        ),
    ]
