# Generated by Django 3.0.7 on 2020-12-19 21:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20201219_2057'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderdetails',
            managers=[
                ('total_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
