# Generated by Django 3.0.7 on 2020-12-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20201219_2136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderdetails',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Итого цена'),
        ),
    ]
