# Generated by Django 3.0.7 on 2020-12-20 10:50

from django.db import migrations


def add_total_price_value(apps, schema_editor):

    OrderDetails = apps.get_model('foodcartapp', 'OrderDetails')
    Product = apps.get_model('foodcartapp', 'Product')
    CustomerOrder = apps.get_model('foodcartapp', 'CustomerOrder')

    for order_details in OrderDetails.objects.all():
        quantity = order_details.quantity

        try:
            product_price = Product.objects.get(id=order_details.product_id).price
        except Product.DoesNotExist:
            print('Empty order details')
            order_details.delete()
            continue

        order_details.total_price = quantity * product_price
        order_details.save()

    for customer_order in CustomerOrder.objects.all():
        order = customer_order.customer_items.all()
        if len(order) == 0:
            print('Empty customer order')
            customer_order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20201219_2328'),
    ]

    operations = [
        migrations.RunPython(add_total_price_value),
    ]
