# Generated by Django 3.0.7 on 2020-12-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20201220_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order_status',
            field=models.CharField(choices=[('NEW_ORDER', 'Необработанный'), ('IN_PROGRESS', 'В работе'), ('DELEVERY', 'Доставка'), ('COMPLETE', 'Выполнен')], default='NEW_ORDER', max_length=15, verbose_name='статус'),
        ),
    ]
