# Generated by Django 3.0.7 on 2020-12-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_customerorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='комментарий'),
        ),
    ]
