# Generated by Django 3.0.7 on 2020-12-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_auto_20201222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_type',
            field=models.CharField(choices=[('ON_LINE', '"Электронно"'), ('CASH', 'Наличными')], default='ON_LINE', max_length=10, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='called_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='в обработке'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='delivered_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='доставлен'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='registrated_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='зарегистрирован'),
        ),
    ]
